PreCommit:
  EsLint:
    enabled: true
    required_executable: './node_modules/.bin/eslint'
    include:
      - 'src/**/*.js'
      - 'src/**/*.jsx'
    exclude:
      - 'flow-typed/*'

  HardTabs:
    enabled: true

  TrailingWhitespace:
    enabled: true
    exclude:
      - 'src/**/*.snap'
